FROM ghcr.io/mvizn/mvizn-docker-images:dockermviznarmg_ppt-flaskdisplay_2025-09-05

# Set the working directory inside the container
WORKDIR /app

# Copy your application code to the container
COPY flaskdisplay/ /app

# Expose port 5000 so the app can be reached externally
EXPOSE 5000

CMD ["/bin/sh", "-c", "python3 flaskdisplay.py 5000 > /dev/null 2>&1"]