#FROM ghcr.io/mvizn/mvizn-docker-images:4.11.0_cuda12.4.1-cudnn-devel-ubuntu22.04
FROM ghcr.io/mvizn/mvizn-docker-images:dockermviznarmg_ppt-mvizn_pptarmg_2025-09-05

EXPOSE 8888

COPY mviznARMG/dotpaddleocr $HOME/.paddleocr

WORKDIR /app
#COPY mviznARMG/ /app

