FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime
# Disable interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install common dependencies
RUN apt-get update && apt-get install -y \
    git ffmpeg libsm6 libxext6 build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install pycocotools and others
RUN pip install cython opencv-python pycocotools matplotlib

# Clone and install Detectron2
RUN git clone https://github.com/facebookresearch/detectron2.git && \
    pip install -e detectron2

# Optional: to verify
RUN python -m detectron2.utils.collect_env

RUN apt-get update && \
    apt-get install -y screen expect tcl libtcl8.6 && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    python3-pip python3-dev python3-venv \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install "numpy==1.26.4" 
RUN pip3 install --no-cache-dir jupyterlab
RUN pip3 install GPUtil
ARG USER_ID=1000
ARG GROUP_ID=1000

# Create matching user and group
RUN groupadd -g ${GROUP_ID} hostgroup && \
    useradd -m -u ${USER_ID} -g ${GROUP_ID} hostuser

# Switch to the new user
USER hostuser
ENV HOME=/home/hostuser
RUN mkdir -p ${HOME}

RUN mkdir -p ${HOME}/.jupyter && \
    echo 'c.NotebookApp.password = "argon2:$argon2id$v=19$m=10240,t=10,p=8$5GhCB4190ff+ssPENRxxjg$G/yOiYB9U79goFRvRmXqNg"' > ${HOME}/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.token = ''" >> ${HOME}/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.ip = '0.0.0.0'" >> ${HOME}/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.open_browser = False" >> ${HOME}/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.port = 8888" >> ${HOME}/.jupyter/jupyter_notebook_config.py
EXPOSE 8888

WORKDIR $HOME
